### ISSUE TITLE
Please fix Postgres bug unserialise function

### ISSUE THREAD

**Issue by V1os** [jlorente/yii2-command-handler#1]
https://github.com/mpociot/versionable/issues/12

DB - postgresql any version
Trace:
PHP Warning 'yii\base\ErrorException' with message 'unserialize() expects parameter 1 to be string, resource given'

in /var/vhost/market/rest-app/vendor/jlorente/yii2-command-handler/src/db/CommandMapper.php:99

Stack trace:
#0 /var/vhost/market/rest-app/vendor/jlorente/yii2-command-handler/src/base/CommandProcessor.php(128): jlorente\command\db\CommandMapper->getCommand()
#1 /var/vhost/market/rest-app/vendor/jlorente/yii2-command-handler/src/base/CommandProcessor.php(109): jlorente\command\base\CommandProcessor->processMapper()
#2 /var/vhost/market/rest-app/vendor/jlorente/yii2-command-handler/src/controllers/CommandProcessorController.php(31): jlorente\command\base\CommandProcessor->run()
#3 /var/vhost/market/rest-app/vendor/yiisoft/yii2/base/InlineAction.php(57): jlorente\command\controllers\CommandProcessorController->actionRun()
#4 /var/vhost/market/rest-app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/vhost/market/rest-app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#5 /var/vhost/market/rest-app/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams()
#6 /var/vhost/market/rest-app/vendor/yiisoft/yii2/console/Controller.php(128): jlorente\command\controllers\CommandProcessorController->runAction()
#7 /var/vhost/market/rest-app/vendor/yiisoft/yii2/base/Module.php(523): jlorente\command\controllers\CommandProcessorController->runAction()
#8 /var/vhost/market/rest-app/vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application->runAction()
#9 /var/vhost/market/rest-app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#10 /var/vhost/market/rest-app/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest()
#11 /var/vhost/market/rest-app/yii(20): yii\console\Application->run()
#12 {main}

**Comment by V1os** [comment]
vendor/jlorente/yii2-command-handler/src/db/CommandMapper.php:96

return unserialize(is_resource($this->command) ? stream_get_contents($this->command) : $this->command, ['allowed_classes' => false]);

**Comment by jlorente** [comment]
I agree with the solution of checking if the property is a resource, but why are you setting allowed_classes to false?

**Comment by V1os** [comment]
Sorry, it's a my lost functionality. Don't take note.

**Comment by jlorente** [comment]
Ok, thanks for the contribution, I wil fix it.
